Punctualize:
  username: Punctualize
  password: st4rw4rs

TwitTree:
  username: twit_tree
  password: st4rw4rs
  
Blockaid:
  username: blockaid
  password: st4rw4rs
  
Backdraft:
  username: _backdraft
  password: st4rw4rs